----  DAY 13 :- CTAS -> CREATE TABLE AS SELECT  ----

--Create a new table based on the result of an SQL query

-- USE CASES -

--1)Optimize Performance
--2)Creating a sanpshot
--3)Physical Data Marts in DWH

--Create a MonthlyOrders CTAS using Sales.Orders
CREATE TABLE MONTHLYORDERS AS
(
	SELECT 
		DATE_PART('MONTH', Orderdate) OrderMonth,
		COUNT(Orderid) TotalOrders
	FROM SALES.ORDERS
	GROUP BY DATE_PART('MONTH', Orderdate)
)

SELECT * FROM MONTHLYORDERS ORDER BY ORDERMONTH

--Find the running total of sales for each month
CREATE TABLE SALES.MONTHLY_SUMMARY AS
(
	SELECT EXTRACT(MONTH FROM ORDERDATE) ORDERMONTH,
	SUM(SALES),
	COUNT(ORDERID) TOTAL_ORDER,
	SUM(QUANTITY) TOTAL_QUANTITY
	FROM SALES.ORDERS
	GROUP BY EXTRACT(MONTH FROM ORDERDATE)
)
--MAIN QUERY
SELECT ORDERMONTH, SUM,
SUM(SUM) OVER(ORDER BY ORDERMONTH) RUNNING_TOTAL
FROM SALES.MONTHLY_SUMMARY


--Provide TANLE that combines details from table orders, products, customers, employee

CREATE VIEW SALES.ORDER_DETAILS AS
(
	SELECT 
		O.ORDERID, O.ORDERDATE,
		P.PRODUCT, P.CATEGORY,
		CONCAT(COALESCE(C.FIRSTNAME,''),' ', COALESCE(C.LASTNAME,'')) CustomerName,
		CONCAT(COALESCE(E.FIRSTNAME,''), ' ', COALESCE(E.LASTNAME,'')) SALESName, E.DEPARTMENT,
		O.SALES, O.QUANTITY
	FROM SALES.ORDERS O
	
	LEFT JOIN SALES.PRODUCTS P ---> PRODUCT TABLE
	ON P.PRODUCTID = O.PRODUCTID
	
	LEFT JOIN SALES.CUSTOMERS C ---> CUSTOMER TABLE
	ON O.CUSTOMERID = C.CUSTOMERID
	
	LEFT JOIN SALES.EMPLOYEES E ---> EMPLOYEE TABLE
	ON O.SALESPERSONID = E.EMPLOYEEID
)

-- MAIN QUERY
SELECT * FROM SALES.ORDER_DETAILS


--Provide a TABLE for the EV sales team that combines details from all tables and excludes data related to the USA

CREATE TABLE SALES.ORDER_DETAILS_EV AS
(
	SELECT 
		O.ORDERID, O.ORDERDATE,
		P.PRODUCT, P.CATEGORY,
		CONCAT(COALESCE(C.FIRSTNAME,''),' ', COALESCE(C.LASTNAME,'')) CustomerName,
		CONCAT(COALESCE(E.FIRSTNAME,''), ' ', COALESCE(E.LASTNAME,'')) SALESName, E.DEPARTMENT,
		O.SALES, O.QUANTITY
	FROM SALES.ORDERS O
	
	LEFT JOIN SALES.PRODUCTS P ---> PRODUCT TABLE
	ON P.PRODUCTID = O.PRODUCTID
	
	LEFT JOIN SALES.CUSTOMERS C ---> CUSTOMER TABLE
	ON O.CUSTOMERID = C.CUSTOMERID
	
	LEFT JOIN SALES.EMPLOYEES E ---> EMPLOYEE TABLE
	ON O.SALESPERSONID = E.EMPLOYEEID

	WHERE C.COUNTRY != 'USA'
)
-- MAIN QUERY
SELECT * FROM SALES.ORDER_DETAILS_EV
